import type { NextPage } from "next";
import Head from "next/head";
import { AddContacts } from "../components/AddContacts";
import { ContactList } from "../components/ContactList";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddContacts />
      <ContactList />
    </div>
  );
};

export default Home;
